### ISSUE TITLE
Add other high-profile console tools with unique do not track env vars/configs

### ISSUE THREAD

**Issue by leighmcculloch** [sneak/consoledonottrack.com#2]
This is a few other high-profile projects that have do not track environment variables that could be listed as examples, and we could open PRs or issues for.

- [ ] .NET Core: `DOTNET_CLI_TELEMETRY_OPTOUT=1`
   https://docs.microsoft.com/en-us/dotnet/core/tools/telemetry

- [ ] AWS SAM CLI: `SAM_CLI_TELEMETRY=0`
   https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

- [ ] Azure CLI: `AZURE_CORE_COLLECT_TELEMETRY=0`
   https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables

- [ ] Google Cloud CLI: Currently no environment variable.
   https://cloud.google.com/sdk/usage-statistics

**Comment by sneak** [comment]
Awesome, thank you!  I will update the webpage with these soon.
