### ISSUE TITLE
Please don't do this

### ISSUE THREAD

**Issue by tastytea** [sneak/consoledonottrack.com#4]
This initiative gives programmers an excuse to make telemetry opt-out. Furthermore, it requires users to know about this obscure variable.

The proposed deactivation of update functionality is outright dangerous for software that is not installed via a package manager.

Collecting user data without explicit consent is already illegal in the EU. Since it is unlikely that projects and companies distribute 2 different version of a software, one with telemetry activated and one with telemetry deactivated, the legal route seems much more promising and benefits all users.

**Comment by eloydegen** [comment]
I would like to add that if the author is viewing this as a new version of the HTTP header: that one is [no longer recommended](https://en.wikipedia.org/wiki/Do_Not_Track).

**Comment by sneak** [comment]
@eloydegen This is about local software, not accessing network services as a client.  HTTP requires that you send your IP address to a server for HTTP to function.  Local software does not.

**Comment by sneak** [comment]
> This initiative gives programmers an excuse to make telemetry opt-out. Furthermore, it requires users to know about this obscure variable.

Developers are already making telemetry opt-out.

The variables to disable presently it are even more obscure (and package-specific) than this.

**Comment by tastytea** [comment]
> Developers are already making telemetry opt-out, regardless of this project.

And they'll have to answer for it. You serve them an excuse on a silver platter.

>  I don't like it either, but it is fact.

We can change it. But we have to get to the root of the problem, not work around it.

**Comment by sneak** [comment]
People are free to make software as they choose, @tastytea.
