### ISSUE TITLE
Awesome Do Not Track List

### ISSUE THREAD

**Issue by muescha** [sneak/consoledonottrack.com#8]
as a chicken & egg problem to solve before libraries adopt your suggestion this idea comes from comments:

(source: https://github.com/gatsbyjs/gatsby/pull/19528#issuecomment-554544864)

> @sneak I appreciate what you are doing here. And I see that it's having some difficulty taking off (looking at the other libraries PRs). While I believe we are happy to take this I have an idea that might be more beneficial for you to scale this.
> 
> Right now to scale this, you need to get this integrated into enough libraries that it becomes common enough for people to carry the torch forward. Submitting PRs to libraries and landing it seems like it might be hard.
> 
> Another option instead of standardizing on a single env var is to make a script that users can download and it will set global envs for all the libraries.
> 
> So an idea is basically, on your website you have some curl script which downloads and executes something that just does
> 
> ```
> export GATSBY_TELEMETRY_DISABLED=1
> export HOMEBREW_NO_ANALYTICS=1
> export STNOUPGRADE=1
> ```
> 
> The benefits that might occur here is that you will have a central repository and takes zero library buy in from library authors.
> 
> Feel free to ignore this idea, just thought I would throw it out there!

(source: https://github.com/gatsbyjs/gatsby/pull/19528#issuecomment-555032882)

> @sneak I absolutely understand. I'm just spit-balling here. It seems like the path of least resistance here is to not require library authors to respect some specific key, even if it is a good idea to do so.
> 
> The way I see it, users who care about this are going to be more passionate about this than library authors. So if you have a central repository, everyone who is a "supporter" will be a contributor potentially. They'll submit PRs to add some libraries specific env var to the master list, which then everyone gets.
> 
> You can then have your script compare itself against the upstream master to suggest users to re-run it for updates. I'm merely suggesting these things because I've noticed the other PRs you opened were closed and dismissed. [Homebrew/brew#6745](https://github.com/Homebrew/brew/pull/6745), [syncthing/syncthing#6158](https://github.com/syncthing/syncthing/pull/6158)
> 
> Again, I commend this idea and just want to see it work out for you!

(Source: https://github.com/gatsbyjs/gatsby/pull/19528#issuecomment-555110582)

> as an beginning you can start just with a readme or Better an json file which you can post on your website.
> 
> Like an awesome list of don't track environment vars or other commands (Google cloud cli) or settings for opt out and a link to the settings page or info page or something.
> 
> As next step some one can write a utility which consume the json.
> Maybe also some detectors which analyze the package.json and recommend the settings for known npm dependencies.
> 
> If a library implemented the option in source the get a big green checkmark on website
> 
> As I read the comments in other repos for your PR there is an demand for your idea.

**Comment by sneak** [comment]
I wish people would stay on topic in the gatsby PR and stop spamming them with suggestions for this project. That PR is to discuss a specific patch for Gatsby.

**Comment by sneak** [comment]
I don't want to create/maintain a package to meta-index all of the different consent variables.

This project was started specifically and explicitly to avoid doing that.

**Comment by beatcracker** [comment]
> I don't want to create/maintain a package to meta-index all of the different consent variables.

Our paths didn't cross before, but I maintain a project that does exactly this: https://github.com/beatcracker/toptout

I hope you don't mind if I mention it here, so people can find it.
